name: Terraform GCP Deploy

on:
  push:
    branches:
      - main # Modify to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform and GCP CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 # Specify the desired Terraform version
          
      - name: Configure GCP credentials
        run: |
          echo  ${{ secrets.TF_API_TOKEN }} > gcp_key.json
          gcloud auth activate-service-account --key-file=gcp_key.json
          
      - name: Initialize Terraform
        run: terraform init

      - name: Plan Infrastructure
        run: terraform plan
